const Postactions = {
  SET_POST:"SET_POST",
  SET_LIKE:"SET_LIKE",
  GET_POST_LIST:"GET_POST_LIST",
  SET_POST_LIST: 'SET_POST_LIST',
  GET_POST_LIST_USER_ID:"GET_POST_LIST_USER_ID",
  SET_POST_LIST_USER_ID: 'SET_POST_LIST_USER_ID',

 
};

export default Postactions;
