const Messangeractions = {
  GET_PEOPLE_LIST:"GET_PEOPLE_LIST",
  SET_PEOPLE_LIST: 'SET_PEOPLE_LIST',
  GET_PEOPLE_PROFILE:"GET_PEOPLE_PROFILE",
  SET_PEOPLE_PROFILE: 'SET_PEOPLE_PROFILE',
  SET_FOLLOW_PEOPLE: 'SET_FOLLOW_PEOPLE',
  SET_UNFOLLOW_PEOPLE: 'SET_UNFOLLOW_PEOPLE',
  GET_FOLLOWING_PEOPLE_LIST:"GET_FOLLOWING_PEOPLE_LIST",
  SET_FOLLOWING_PEOPLE_LIST: 'SET_FOLLOWING_PEOPLE_LIST',
  GET_FOLLOWERS_PEOPLE_LIST:"GET_FOLLOWERS_PEOPLE_LIST",
  SET_FOLLOWERS_PEOPLE_LIST: 'SET_FOLLOWERS_PEOPLE_LIST',
 
};

export default Messangeractions;
