const actions = {
  GET_AUTHETICATRION:"GET_AUTHETICATRION",
  SET_AUTHETICATRION: 'SET_AUTHETICATRION',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  REGISTER_USER: "REGISTER_USER",
  // SET_VERIFY_TOCKET: 'SET_AUTHETICATRION',
  GET_VERIFY_TOCKET:"GET_AUTHETICATRION",
  UPDATE_USER_DETAILS:"UPDATE_USER_DETAILS",
  SET_LOADER:"SET_LOADER",
  SET_REGISTER_NAVIGATE:"SET_REGISTER_NAVIGATE",
  SET_LOGIN_MESSAGE:"SET_LOGIN_MESSAGE"
};

export default actions;
